spring.application.name=demosec

################ SERVER ################
server.port=8081
server.servlet.context-path=/springsecurity

################ DATABASE ################
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/demospringsecurity?createDatabaseIfNotExist=true&serverTimezone=Africa/Tunis
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################ JPA ################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Tunis

################ JWT ################
app.jwt.secret=YOUR_JWT_SECRET_KEY
app.jwt.expiration-ms=3600000

################ MAIL ################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_ADDRESS
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

################ SMS / TWILIO ################
sms.enabled=true
twilio.account-sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth-token=YOUR_TWILIO_AUTH_TOKEN
twilio.from-number=YOUR_TWILIO_PHONE_NUMBER
